
# Create a docker-compose.yml file
version: '3.8'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=SCU_Schedule_Gen
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: